### ISSUE TITLE
Wildcard is not handled in sysdep

### ISSUE THREAD

**Issue by Tiger3018** [ros-infrastructure/rosindex#325] opened 2023-10-26 18:50 UTC
e.g. <https://index.ros.org/d/embree/> and <https://github.com/ros/rosdistro/blob/f1e4bf3/rosdep/base.yaml#L932>

```
{"arch"=>["embree"], "debian"=>{"bullseye"=>["libembree-dev"]}, "fedora"=>["embree"], "nixos"=>["embree"], "ubuntu"=>{"*"=>["libembree-dev"], "bionic"=>nil}}
```

![image](https://github.com/ros-infrastructure/rosindex/assets/31267153/2bfc09ee-b17e-46f9-8908-f86806dab363)

It's evident that the wildcard standing for distro version is not handled decently.

**Comment by tfoote** [comment] 2023-11-29 01:52
Thanks yes, this is a duplicate of #275

**Closed as completed by tfoote** 2023-11-29 01:52 UTC
