### ISSUE TITLE
$ ros2 run ros1_bridge dynamic_bridge        =~=      "No executable found"

### ISSUE THREAD

**Issue by Pritish9** [ros-infrastructure/rosindex#165] opened 2019-06-10 03:31 UTC
After installing ros-dashing-desktop, for install ros-dashing-ros1-bridge in ran:
$ sudo apt-get install ros-dashing-ros1-bridge
Doing so ros1_bridge was installed but there were no executable found. 

There is no ros1_bridge directory in /opt/ros/dashing/lib/.

Doing the above commands did work for crystal (but not dashing).

**Comment by dirk-thomas** [comment] 2019-06-10 03:40
Duplicate of ros2-gbp/ros1_bridge-release#4. A fixed package is already in the testing repo and will be in the main repo with the next sync.

**Closed as completed by dirk-thomas** 2019-06-10 03:40 UTC
Labels: duplicate

**Comment by Pritish9** [comment] 2019-06-10 03:53
Thanks appreciate for the response!!
