### ISSUE TITLE
Use sphinx to enable cross referencing

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/rosindex#48] opened 2018-09-20 05:20 UTC
In the meeting it was suggested to consider using sphinx (as described in the existing documentation design document). That would allow to cross reference specific parts of the generated documentation instead of relying on "full" URLs.

**Comment by hidmic** [comment] 2018-09-20 14:04
@dirk-thomas @tfoote I _think_ https://github.com/ros2/design/blob/gh-pages/articles/080_ros_documentation_system.md might be the design document. It's tagged as unpublished though (and thus it doesn't show up in the site).

**Comment by hidmic** [comment] 2018-09-20 14:30
BTW I went over that document. First impression is that, though the documentation system architecture it depicts is _very_ interesting and feature-rich (e.g. it may solve documentation versioning, cross-referencing across files, even resolution against remotes for easy local documentation builds, etc.), it diverges _significantly_ from what we have right now. So while I think we may still be able to shoehorn sphinx into our jekyll scaffolding, referencing some externally served sphinx-generated code documentation, keeping rosindex legacy codebase around may become a burden over time (e.g. as opposed to just extending sphinx to meet our rosindex generation needs). 

Just my two cents. I'd really like to know what you guys think about it.

**Comment by dirk-thomas** [comment] 2018-09-20 16:11
The scope of this ticket wasn't to implement the whole design doc. It was mostly about using Sphinx in order to enable the use of intersphinx inventory files. The `.inv` files should be available under a specific URL and could be used to perform cross documentation linking "cleanly".

**Comment by hidmic** [comment] 2018-09-20 16:47
Right. That's what I was thinking of for a quick addition to `rosindex`. But I still wanted to ask about the design doc and how it relates to the ROS docs effort. Thanks!

Oh, one last thing. Is this Sphinx-generated site up there already? Is it http://docs.ros2.org/?

**Comment by apojomovsky** [comment] 2018-10-11 20:53
Hi @dirk-thomas!
It might be handy for us to count with an already-generated `.inv` file in order to test this new feature. Are you aware of a valid URL from which we can fetch one of these files?

**Comment by dirk-thomas** [comment] 2018-10-11 21:25
E.g. the documentation of the Python packages contain `.inv` files. They are hosted under http://docs.ros.org/independent/api/ but not nicely discoverable (without SSH access to the server). The actually available files relative to the above URL are:

* `catkin_pkg/html/objects.inv`
* `catkin_pkg/objects.inv` (not sure what the difference to the previous one is...)
* `jenkins_tools/html/objects.inv`
* `rosdep/html/objects.inv`
* `rosdistro/html/objects.inv`
* `rosinstall/html/objects.inv`
* `rospkg/html/objects.inv`
* `vcstools/html/objects.inv`

**Comment by dirk-thomas** [comment] 2018-10-12 16:44
@apojomovsky Can you describe / document how existing docs can be referenced now? E.g. where are the `.inv` files which can be used?

**Comment by apojomovsky** [comment] 2018-10-12 17:08
Hi @dirk-thomas .
The PR #75 added the initial support for sphinx in rosindex, which now allows us to add the functionality described in the ticket. I didn't realized that PR closed this issue (I'm reopening it now).
There are still a couple of PRs pending for this to be complete:
- One that adds the support for `.inv` files.
- Another one, this time against [ros2_documentation](https://github.com/ros2/ros2_documentation) with a document that will make use of the cross-reference feature, so that we can see it in action.

Would that make sense?

I'll also make sure to add the required comments / docs for this to be easy to add new `.inv` files.

**Comment by hidmic** [comment] 2018-10-16 14:21
@chapulina @tfoote @apojomovsky #80 came with a surprise. While developing it, I found out that [`recommonmark`](https://recommonmark.readthedocs.io/en/latest/) (i.e. the sphinx extension we're using to read in Markdown files) does not cross link headers across pages e.g. `[..](SomeFile.md#Some-header)`! On top of this, even if it were supported, such URL fragment usage clashes with the distro switch implementation necessary for #45, that also uses fragments but for tracking distros. I've added a throwing check for this to not pass by silently [here](https://github.com/ros2/rosindex/pull/80/files#diff-dac9c27c21ed6bc48485c0e6ed3dbb92R132), but **it means we must remove all of these links from our documentation pages**.

The easy way out is to abandon Markdown for good and migrate documentation to ReST. Sphinx's community support for Markdown is quite poor anyways (e.g. table markup is broken, we do it manually). Alternatively, we _might_ be able to improve a `recommonmark` fork to support Markdown header links (assuming it's possible and it's currently not supported just because the author didn't think it was worth adding it) and redesign the distro switch to not use URL fragments for distro tracking (effectively ditching #80 and starting over). 

Given we're quite time constrained I'd argue for the first option, but since we were aiming to support both markup formats this may come as a significant regression and a no-go in longer term. But that I don't know.

cc @dirk-thomas for awareness.

**Comment by apojomovsky** [comment] 2018-10-16 18:30
+1 to abandon `Markdown` in favor or `ReST`.
On top of what Michel just mentioned, I stumbled upon another issue related to `markdown` + `Sphinx` incompatibilities: 
After a couple of hours of trial/error I was unable to find a way to make `Sphinx` to correctly resolve inter-sphinx links from `md` files, they work flawlessly when invoked from within `rst` files though.
We dug a bit into `recommonmark`'s source code to see if it was treating the inter-sphinx links erroneously but it was not the case, this is more a Sphinx specific thing.

**Comment by tfoote** [comment] 2018-10-16 18:41
I like markdown better, but if ReST has better integration and just works I'd agree stick with that for the documentation. As long as we can still render markdown from README's which are very common.

**Comment by hidmic** [comment] 2018-10-25 13:28
Addressed by #88. Documentation added in ros2/ros2_documentation#6.

**Closed as completed by hidmic** 2018-10-25 13:28 UTC
Labels: enhancement
