### ISSUE TITLE
Q&A tab fails to list questions due to RSS feed parsing error

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#94] opened 2018-10-24 22:45 UTC
See the [deployed RViz page](https://index.ros.org/p/rviz/github-ros-visualization-rviz/#melodic-questions) for example, it's empty after `Answers.ros.org Recent Questions Tagged: rviz`, but there are clearly [many questions tagged rviz](https://answers.ros.org/questions/scope:all/sort:activity-desc/tags:rviz/page:1/).

![rvizqa](https://user-images.githubusercontent.com/5751272/47465801-4f9b0280-d7a3-11e8-8b48-5fe06ec98f3c.png)

I'm not sure if the problem is in the code or in the deployment. I also noticed that [rosindex.github.io](http://rosindex.github.io/p/rviz/) doesn't have `Q&A` tabs.

**Comment by tfoote** [comment] 2018-10-25 00:11
It is supposed to work. And it does work for other packages such as tf2: https://index.ros.org/p/tf2/#kinetic-questions

![image](https://user-images.githubusercontent.com/447804/47468353-ac041f00-d7af-11e8-961a-9371afda12e4.png)


There's a bug somewhere in there, because even if there's not any matches, it should still show the link to ask a question:

![image](https://user-images.githubusercontent.com/447804/47468387-d5bd4600-d7af-11e8-967e-0b283a53c4c9.png)

**Comment by hidmic** [comment] 2018-10-25 15:46
Just checked at index.ros.org, it seems one of the questions tagged with `rviz` came with a funky character and the browser complained:

![ill_formed_xml](https://user-images.githubusercontent.com/13500507/47512997-bf68c600-d853-11e8-856a-1eba3ee266e5.png)

Culprit is:
```
[ INFO] [1536482904.742637273]: GLRenderSystem::_createRenderWindow "OgreWindow(0)", 1x1 windowed  miscParams: FSAA=4 contentScalingFactor=1,000000 externalGLControl= externalWindowHandle=50331649 parentWindowHandle=50331649 
```

Maybe we can encode it somehow? Though we won't get rid of the error log coming from the RSS library.

**Comment by hidmic** [comment] 2018-10-26 13:53
Read a bit more, I think the problem is the RSS feed itself that's generating bad XML.

**Comment by hidmic** [comment] 2019-01-08 17:35
Addressed already. Closing this one.

**Closed as completed by hidmic** 2019-01-08 17:35 UTC
