### ISSUE TITLE
ros2 overview pages are missing except for the home page

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#102] opened 2018-10-26 04:04 UTC
Somewhere in the recent tweaks all the pages from the ros2 overview have been lost except the index.html 

https://github.com/ros-infrastructure/index.ros.org/tree/gh-pages/doc/ros2_overview

![image](https://user-images.githubusercontent.com/447804/47543876-2b215200-d899-11e8-9a24-065e3bde2226.png)

They appear to be generated and written, but aren't in the resulting repo.

From: http://build.ros.org/job/doc_rosindex/7/consoleFull
```
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Features/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/DDS-and-ROS-middleware-implementations/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Build-Cop-and-Build-Farmer-Guide/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Managed-Nodes/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/OSX-Development-Setup/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Linux-Development-Setup/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Inter-Sphinx-Support/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/catment/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Building-Realtime-rt_preempt-kernel-for-ROS-2/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Set-up-a-new-Windows-CI-node/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/dummy-robot-demo/index.html
00:59:02.131            Writing: /tmp/upload_repository/doc/ros2_overview/Quality-Guide/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Logging/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Migration-Guide/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/New-features-in-ROS-2-interfaces-(msg-srv)/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Intel-ROS2-Projects/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Run-2-nodes-in-a-single-docker-container/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Tutorials/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Beta3-Overview/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Rosidl-Tutorial/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Overview-of-ROS-2-concepts/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Alpha-Overview/index.html
00:59:02.132            Writing: /tmp/upload_repository/doc/ros2_overview/Releasing-a-ROS-2-package-with-bloom/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/tf2/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Contact/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Launch-system/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Fedora-Development-Setup/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/About/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/ROS-2-On-boarding-Guide/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Beta2-Overview/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/OSX-Install-Binary/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Releases/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Intra-Process-Communication/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/About-Quality-of-Service-Settings/index.html
00:59:02.133            Writing: /tmp/upload_repository/doc/ros2_overview/Beta1-Overview/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Rosbag-with-ROS1-Bridge/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Building-ROS-2-on-Linux-with-Eclipse-Oxygen/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Real-Time-Programming/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Colcon-Tutorial/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Developer-Guide/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Allocator-Template-Tutorial/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Python-Programming/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Set-up-a-new-Linux-CI-node/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Ament-Tutorial/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Installation/index.html
00:59:02.134            Writing: /tmp/upload_repository/doc/ros2_overview/Logging-and-logger-configuration/index.html
00:59:02.135            Writing: /tmp/upload_repository/doc/ros2_overview/Release-Ardent-Apalone/index.html
00:59:02.135            Writing: /tmp/upload_repository/doc/ros2_overview/Set-up-a-new-macOS-CI-node/index.html
00:59:02.135            Writing: /tmp/upload_repository/doc/ros2_overview/Release-Howto/index.html
00:59:02.135            Writing: /tmp/upload_repository/doc/ros2_overview/About-ROS-Interfaces/index.html
00:59:02.135            Writing: /tmp/upload_repository/doc/ros2_overview/index.html
00:59:02.135            Writing: /tmp/upload_repository/doc/ros2_overview/Quality-of-Service/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Node-arguments/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Rclpy-Import-error-hint/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Eclipse-Oxygen-with-ROS-2-and-rviz2/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Windows-Development-Setup/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Contributing/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Working-with-multiple-RMW-implementations/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Design-Guide/index.html
00:59:02.136            Writing: /tmp/upload_repository/doc/ros2_overview/Maintaining-a-Source-Checkout/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Install-Connext-Security-Plugins/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Composition/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Linux-Install-Binary/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Defining-custom-interfaces-(msg-srv)/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Release-Bouncy-Bolson/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Linux-Install-Debians/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/CI-Server-Setup/index.html
00:59:02.137            Writing: /tmp/upload_repository/doc/ros2_overview/Roadmap/index.html
00:59:02.138            Writing: /tmp/upload_repository/doc/ros2_overview/ROS-2-Client-Libraries/index.html
00:59:02.138            Writing: /tmp/upload_repository/doc/ros2_overview/MISRA-Compliance-Guide/index.html
00:59:02.138            Writing: /tmp/upload_repository/doc/ros2_overview/Introspection-with-command-line-tools/index.html
00:59:02.138            Writing: /tmp/upload_repository/doc/ros2_overview/Windows-Install-Binary/index.html
```

**Comment by hidmic** [comment] 2018-10-26 13:55
Hmm, I cannot reproduce this locally.

**Comment by hidmic** [comment] 2018-10-26 16:38
@tfoote could you share a tree view of `repository` inside the the job workspace?

**Comment by chapulina** [comment] 2018-10-26 17:40
The [latest deployment](http://build.ros.org/job/doc_rosindex/8/consoleFull) is in an even worse state, even the entry page, https://index.ros.org/doc/ros2 doesn't come up.

As before, you can see on the logs that the pages were generated, but they weren't committed to [the repo](https://github.com/ros-infrastructure/index.ros.org).

Maybe the files are not being added when `git commit`ing?

**Closed as completed** 2018-10-26 18:07 UTC
Labels: bug
