### ISSUE TITLE
contribute suggestion render errors

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#213] opened 2020-01-23 03:24 UTC
The contribute suggestions pages have rendering errors and the pagination goes to 10 pages despite there only being 3 in the list. 

![Screenshot from 2020-01-22 19-20-38](https://user-images.githubusercontent.com/447804/72954187-69cbe380-3d4c-11ea-865b-f8a3faae00e5.png)

http://build.ros.org/job/doc_rosindex/375/consoleText
```
Rendering: contribute/suggestions/page/1/name/index.html
  Pre-Render Hooks: contribute/suggestions/page/1/name/index.html
  Rendering Liquid: contribute/suggestions/page/1/name/index.html
[1;33m    Liquid Warning: Liquid syntax error (line 60): Unexpected character { in "{{{{suggestion[0]}} }}" in contribute/suggestions/page/1/name/index.html[0m
[1;33m    Liquid Warning: Liquid syntax error (line 113): Unexpected character { in "{{{{suggestion[0]}} }}" in contribute/suggestions/page/1/name/index.html[0m
  Rendering Markup: contribute/suggestions/page/1/name/index.html
  Rendering Layout: contribute/suggestions/page/1/name/index.html
     Layout source: site
         Rendering: contribute/suggestions/index.html
  Pre-Render Hooks: contribute/suggestions/index.html
  Rendering Liquid: contribute/suggestions/index.html
[1;33m    Liquid Warning: Liquid syntax error (line 60): Unexpected character { in "{{{{suggestion[0]}} }}" in contribute/suggestions/index.html[0m
[1;33m    Liquid Warning: Liquid syntax error (line 113): Unexpected character { in "{{{{suggestion[0]}} }}" in contribute/suggestions/index.html[0m
  Rendering Markup: contribute/suggestions/index.html
  Rendering Layout: contribute/suggestions/index.html
     Layout source: site
         Rendering: contribute/suggestions/page/1/time/index.html
  Pre-Render Hooks: contribute/suggestions/page/1/time/index.html
  Rendering Liquid: contribute/suggestions/page/1/time/index.html
[1;33m    Liquid Warning: Liquid syntax error (line 60): Unexpected character { in "{{{{suggestion[0]}} }}" in contribute/suggestions/page/1/time/index.html[0m
[1;33m    Liquid Warning: Liquid syntax error (line 113): Unexpected character { in "{{{{suggestion[0]}} }}" in contribute/suggestions/page/1/time/index.html[0m
```

@max-krichenbauer this looks like an issue with #194

**Comment by max-krichenbauer** [comment] 2020-01-23 04:52
Sorry about that.
I'm actually unable to reproduce the rendering issues here. (Maybe a Jekyll version difference?) But the warning did indicate broken code that may have been the cause.
I also fixed the page number.
PR is [here](https://github.com/ros-infrastructure/rosindex/pull/215).
Sorry again for the trouble.

**Comment by hidmic** [comment] 2020-01-28 12:04
Since #215 is merged, and the issue appears to be fixed at https://index.ros.org/contribute/suggestions, I'll close this.

**Closed as completed by hidmic** 2020-01-28 12:04 UTC
Labels: bug
